### PR TITLE
Build MMS on Circleci

### PR DESCRIPTION
**Pull request by prashantsail**
## Description of changes:
First cut for - MMS builds using CircleCI

This PR contains -
1. CircleCI config (_.circleci/config.yml_)
2. Current CircleCI configuration includes :
    - 1 frontend build job
    - Followed by 4 parallel execution of test jobs
    - 1 independent model-archiver build & test job
    - Checkout how the MMS project and build/job configuration looks like on  [CircleCI webapp](https://app.circleci.com/pipelines/github/prashantsail/multi-model-server)
3. Scripts (_.circleci/scripts/*.sh_) triggered from CircleCI Jobs to build and test MMS
4. Two new testsuites have also been added to validate their integration with CircleCI
    - newman testsuite (_test/*_)
        postman api tests from pytorch/serve were ported and tweaked to work with mms
5. Docker images (_.circleci/images/*_)
    - To avoid redundant dependency installation steps and to save build time, I created my own docker image (with pre-installed dependencies).
    - These are based off awsdeeplearningteam/mms-build:python* images available on docker hub
    - Need help moving images from under my(prashantsail) repository in dockerhub to awsdeeplearningteam
6. Local execution (_./run_circleci_tests.py_)
    Devs can run circleci jobs on their local machine, using this single script

More details are available in the _.circleci/README.md_

## Testing done:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by prashantsail** [comment]
In the latest commit, added support for build and test across python 2.7 & 3.6 environment.

**Comment by dhanainme** [comment]
Please add logs / Screenshots of Circle CI report.

**Comment by prashantsail** [comment]
> Please add logs / Link & screenshot of Circle CI report.

@dhanainme 

### Screenshot

image

### Links

1. [Smoke](https://app.circleci.com/pipelines/github/prashantsail/multi-model-server/357/workflows/e8df3d95-8315-4c13-bd01-9234cdd2dab1)(triggered per commit)
2. [Nightly](https://app.circleci.com/pipelines/github/prashantsail/multi-model-server/355/workflows/84b521bd-d536-4d6e-904c-3226debcc090) 

### Logs and Results
| JOBS                  | LOGS | RESULTS |
|-----------------------|------|---------|
| Frontend Gradle tests | [logs](https://app.circleci.com/pipelines/github/prashantsail/multi-model-server/357/workflows/e8df3d95-8315-4c13-bd01-9234cdd2dab1/jobs/1018/parallel-runs/0/steps/0-102) | [results](https://app.circleci.com/pipelines/github/prashantsail/multi-model-server/357/workflows/e8df3d95-8315-4c13-bd01-9234cdd2dab1/jobs/1018/artifacts) |
| Python Tests          | [logs](https://app.circleci.com/pipelines/github/prashantsail/multi-model-server/357/workflows/e8df3d95-8315-4c13-bd01-9234cdd2dab1/jobs/1020/parallel-runs/0/steps/0-102) | [results](https://app.circleci.com/pipelines/github/prashantsail/multi-model-server/357/workflows/e8df3d95-8315-4c13-bd01-9234cdd2dab1/jobs/1020/artifacts) |
| API Tests             | [logs](https://app.circleci.com/pipelines/github/prashantsail/multi-model-server/355/workflows/84b521bd-d536-4d6e-904c-3226debcc090/jobs/1012/parallel-runs/0/steps/0-106) | [results](https://app.circleci.com/pipelines/github/prashantsail/multi-model-server/355/workflows/84b521bd-d536-4d6e-904c-3226debcc090/jobs/1012/artifacts) |

**Comment by dhanainme** [comment]
Have review this. This looks good to me. 

I ll have this merged tomorrow.

**Pull request merged**
